# Add configuration values here, as shown below.
#
harvest_account_1_id: email1@example.com
harvest_account_1_key: secret1
harvest_account_2_id: email2@example2.com
harvest_account_2_key: secret2
#
# production:
#   harvest_account_1_id: email1@example.com
#   harvest_account_1_key: secret1
#   harvest_account_2_id: email2@example2.com
#   harvest_account_2_key: secret2
